dependencies:
  - cdsapi
  - numpy
  - netCDF4
  - xarray
  - matplotlib
  - cartopy
  - jupyterlab-myst
  - eccodes
  - jupyterlab
  - ipykernel
  - rioxarray
  - pip
  - pip:
    - earthkit==1.0.0rc1
    - eckitlib
    - mirlib
    - mir-python
    - eckit
    - eccodeslib

